"""Increase password_hash field length

Revision ID: 7579a634280b
Revises: b4b2d399b9ef
Create Date: 2025-05-04 08:07:40.444091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7579a634280b'
down_revision = 'b4b2d399b9ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
